name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      working-directory: ./tests

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@master
      - uses: nanasess/setup-chromedriver@master
        with:
          chromedriver-version: '77.0.3865.40'
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
          
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run npm install
        run: npm install
        working-directory: ${{env.working-directory}}

      - name: Run npm test
        run: npm run gh-actions-test
        working-directory: ${{env.working-directory}}
